const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),ts=require(root+'/node_modules/typescript');
function load(file,context){const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(root+'/'+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{module:mod,exports:mod.exports,...context});return mod.exports;}
(async()=>{
 let sdkCount=0,requests=0,clearCount=0,paired=false;
 const sdkModule={DiscordSDK:class{constructor(){sdkCount++;this.channelId="1066471931542507624";this.instanceId="shared-instance"}ready(){return Promise.resolve()}}};
 const api=load('app/lib/discordClient.ts',{process:{env:{NEXT_PUBLIC_DISCORD_CLIENT_ID:"fixture"}},URLSearchParams,sessionStorage:{getItem:key=>key==="lgc.discord.paired" ? (paired?"1":null) : "?frame_id=frame&channel_id=1066471931542507625"},window:{location:{search:"?multiplayer=1"},setTimeout,clearTimeout:id=>{clearCount++;clearTimeout(id)}},URL,AbortSignal,fetch:async()=>{requests++;return{ok:true,json:async()=>({session_token:'isolated-session'})}},require:name=>{assert.equal(name,'@discord/embedded-app-sdk');return sdkModule}});
 const [one,two]=await Promise.all([api.getDiscordSdk('fixture'),api.getDiscordSdk('fixture')]);assert.equal(one,two);assert.equal(sdkCount,1);assert.equal(await api.getDiscordSdk('fixture'),one);console.log('PASS one SDK instance across simultaneous consumers and route revisits');
 const call=await api.getDiscordCall();assert.equal(call.sdk,one);assert.equal(call.channelId,'1066471931542507624');assert.equal(call.instanceId,'shared-instance');assert.equal(sdkCount,1);console.log('PASS roguelike retains Activity context across navigation and uses the SDK call identity');
 paired=true;const pairedCall=await api.getDiscordCall();assert.equal(pairedCall.channelId,'1066471931542507625');assert.equal(pairedCall.sdk,null);paired=false;console.log('PASS mobile pairing retains call matching when Discord RPC is unavailable');
 const results=await Promise.all([api.exchangeDiscordCode('fixture-code','https://rchqwk.com'),api.exchangeDiscordCode('fixture-code','https://rchqwk.com')]);assert.equal(requests,1);assert.equal(results[0].session_token,'isolated-session');await api.exchangeDiscordCode('fixture-code','https://rchqwk.com');assert.equal(requests,1);console.log('PASS callback remounts do not consume a single-use OAuth code twice');
 await assert.rejects(api.withDiscordTimeout(new Promise(()=>{}),'handshake timed out',1),/handshake timed out/);await api.withDiscordTimeout(Promise.resolve('ready'),'timeout',20);assert(clearCount>0);console.log('PASS hung handshake terminates and completed handshakes clear their timer');
 assert.equal(api.discordReturnPath('1066471931542507624'),'/casino/blackjack-v2/1066471931542507624');assert.equal(api.discordReturnPath('/casino/blackjack-v2/discord?frame_id=old'),'/casino/blackjack-v2');assert.equal(api.discordReturnPath('//evil.example'),'/casino/blackjack-v2');assert.equal(api.discordReturnPath('/casino/profile?code=secret&frame_id=old'),'/casino/profile');console.log('PASS callback returns are local, remove auth parameters, and cannot re-enter the auth route');
 const redirects=[];const home=load('app/page.tsx',{URLSearchParams,require:name=>{if(name==='next/navigation')return{redirect:target=>{redirects.push(target);throw Error('redirect')}};if(name==='react/jsx-runtime')return{jsx:(type,props)=>({type,props})};if(name==='./components/DiscordRootCallback')return{DiscordRootCallback:'callback'};throw Error(name)}}).default;
 const callback=await home({searchParams:Promise.resolve({code:'isolated-code',state:'mobile:ISOLATED'})});assert.equal(callback.props.code,'isolated-code');assert.equal(callback.props.state,'mobile:ISOLATED');
 await assert.rejects(home({searchParams:Promise.resolve({frame_id:'frame',instance_id:'instance',platform:'desktop',channel_id:'1066471931542507624'})}),/redirect/);assert(redirects[0].includes('frame_id=frame')&&redirects[0].includes('channel_id=1066471931542507624'));console.log('PASS async root query preserves OAuth callbacks and Activity launch parameters');
})().catch(error=>{console.error(error);process.exitCode=1});
